Rewrote mystmod to be able to run --setup on its own.
- Now mystmod can run --setup in conjunction with the --install flag, or after --install of a module has already been done.

Also:

- Added additional checks in tests/mksite to make sure that setup code is triggered correctly.

diff --git a/tests/mksite b/tests/mksite
--- a/tests/mksite
+++ b/tests/mksite
@@ -5,7 +5,7 @@
 
 # use regular script rules to set up and tear down things
 
-if [ 0 -eq 1 ]
+if [ 1 -eq 1 ]
 then
 	rm -rf /srv/http/shalamar.local
 	mysql -u root -e 'drop database shalamar_db' 2>/dev/null
@@ -19,38 +19,52 @@ fi
 if [ 1 -eq 1 ]
 then
 
-
-echo 'myst --create --name shalamar -f /srv/http/shalamar.local -m shalamar.local --ses --apache --description "Yet another test site." --datasource shalamar_db'
-myst --create --name shalamar -f /srv/http/shalamar.local -m shalamar.local --ses --apache --description "Yet another test site." --datasource shalamar_db
-read
+	echo 'myst --create --name shalamar.local -f /srv/http/shalamar.local -m shalamar.local --ses --apache --description "Yet another test site." --datasource shalamar_db'
+	myst --create --name shalamar.local -f /srv/http/shalamar.local -m shalamar.local --ses --apache --description "Yet another test site." --datasource shalamar_db
+	read
 
 # Why does a name need to specified?
-echo 'myst --folder /srv/http/shalamar.local --finalize'
-myst --folder /srv/http/shalamar.local --finalize
-read
+	echo 'myst --folder /srv/http/shalamar.local --finalize'
+	myst --folder /srv/http/shalamar.local --finalize
+	read
 
 # Activate this for use with Apache
-echo 'sudo cp /srv/http/shalamar.local/misc/apache.vhost /etc/httpd/conf/extra/vhosts-available/shalamar.local'
-sudo cp /srv/http/shalamar.local/misc/apache.vhost /etc/httpd/conf/extra/vhosts-available/shalamar.local
-echo 'sudo ln -s /etc/httpd/conf/extra/vhosts-available/shalamar.local /etc/httpd/conf/extra/vhosts-enabled/'
-sudo ln -s /etc/httpd/conf/extra/vhosts-available/shalamar.local /etc/httpd/conf/extra/vhosts-enabled/
-read
-
+	echo 'sudo cp /srv/http/shalamar.local/misc/apache.vhost /etc/httpd/conf/extra/vhosts-available/shalamar.local'
+	sudo cp /srv/http/shalamar.local/misc/apache.vhost /etc/httpd/conf/extra/vhosts-available/shalamar.local
+	echo 'sudo ln -s /etc/httpd/conf/extra/vhosts-available/shalamar.local /etc/httpd/conf/extra/vhosts-enabled/'
+	sudo ln -s /etc/httpd/conf/extra/vhosts-available/shalamar.local /etc/httpd/conf/extra/vhosts-enabled/
 
 # Create a datasource
-echo 'mystdb --create --generate -f /srv/http/shalamar.local --mysql --verbose --name shalamar_db --user root'
-mystdb --create --generate -f /srv/http/shalamar.local --mysql --verbose --name shalamar_db --user root
-read
+	echo 'mystdb --create --generate -f /srv/http/shalamar.local --mysql --verbose --name shalamar_db --user root'
+	mystdb --create --generate -f /srv/http/shalamar.local --mysql --verbose --name shalamar_db --user root
+	read
+
+# Finally, restart the server
+	echo 'sudo systemctl restart httpd && sudo systemctl restart lucee'
+	sudo systemctl restart httpd && sudo systemctl restart lucee
+	read
 
 # Add a module (cms)... 
-echo 'mystmod --install /srv/http/repo.mystframework.local/repo/cms --to /srv/http/shalamar.local'
-mystmod --install /srv/http/repo.mystframework.local/repo/cms --to /srv/http/shalamar.local
-read
+	echo 'mystmod --install /srv/http/repo.mystframework.local/repo/cms --to /srv/http/shalamar.local'
+	mystmod --install /srv/http/repo.mystframework.local/repo/cms --to /srv/http/shalamar.local
+	read
 
 # ...and set it up
-echo 'mystmod --setup --address http://shalamar.local'
-mystmod --setup --address http://shalamar.local
-read
+	echo 'mystmod --setup --address http://shalamar.local'
+	mystmod --setup --address http://shalamar.local
+	read
 
+fi
 
+# Check that everything took
+if [ 1 -eq 1 ]
+then
+# Is the instance there?
+	[ -d /srv/http/shalamar.local ] || echo "TEST FAILED: Failed to create instance..." 
+# Is the datasource specified in the instance?
+	[ ! -z `grep shalamar_db /srv/http/shalamar.local/Application.cfc 2>/dev/null` ] || echo "TEST FAILED: Failed to add datasource..." 
+# Can I get a packet from the server?
+	wget -O- http://shalamar.local
+# Did MySQL load tables?
+	mysql -u root -e 'use shalamar_db; show tables;'
 fi
